### ISSUE TITLE
Infinite zoom

### ISSUE THREAD

**Issue by karaarda** [arlindiDev/FrescoDoubleTapZoom#1]
You can zoom for ever, it is not really good. Can you find a solution for this

**Comment by arlindiDev** [comment]
hmmm I'll have to check to set a maximum zoom level thanks for writing an issue :)

**Comment by karaarda** [comment]
I solved the problem, change limitScale with this one: 

```
private float limitScale(float pivotX, float pivotY)
    {
        float scale = -1.0f;

        float currentScale = getScaleFactor();
        float targetScale = limit(currentScale, mMinScaleFactor, mMaxScaleFactor);
        if (targetScale != currentScale) {
            scale = targetScale / currentScale;
            mActiveTransform.postScale(scale, scale, pivotX, pivotY);
        } else
            scale = currentScale;

        return scale;
    }
```

And I highly recommend you to update your code base with Fresco's lates code. There several bugs in current one:
1. Fling does not work
2. Double tap sometimes cast as 2 different single taps
3. DoubleTap listener does not get called sometimes at all

**Comment by arlindiDev** [comment]
@senhor can you fix this and push it to this repository

**Comment by karaarda** [comment]
why not

**Comment by arlindiDev** [comment]
I haven't maintained this project in while I think you probably have more knowledge since your working with Fresco and this project :)

**Comment by karaarda** [comment]
I will try my best :)

**Comment by arlindiDev** [comment]
I added you as a collaborator to the project

**Comment by karaarda** [comment]
thanks
